FROM python:3.10-buster

ENV PYTHONUNBUFFERED 1

# EXPOSE $PORT

RUN mkdir /code
WORKDIR /code
COPY ./library_back .

COPY ./docker/library_back_entrypoint.sh ./library_back_entrypoint.sh

RUN ["chmod", "+x", "./library_back_entrypoint.sh"]

RUN pip3 install --upgrade pip==21.* && \
    pip3 install -r requirements.txt

ENTRYPOINT ["./library_back_entrypoint.sh"]

# CMD [ "python3", "manage.py", "runserver" ]
