# This is a CI worflow to check Build, Test and Lint to library project

name: CI - Build/Test/Lint library project

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # Runs build of application with docker-compose
      - name: Run a detached build and up of project
        run: docker-compose up -d

  test-front:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs test of front with docker-compose
      - name: Run a detached build and up of project
        run: docker-compose run library-front yarn ci:test
